### ISSUE TITLE
changes path from /players/games/{id}  to /players/{id}/games/ -- auth-path pattern alternative is required

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices#28]
**Current validation logic:**

- [x] a change on this logic is required? No need

```
private List<HttpRequestDTO> paths;


    public boolean isAdminPath(HttpRequestDTO httpRequestDTO) {
        return paths.stream().anyMatch(path ->
                Pattern.matches(path.getUri(), httpRequestDTO.getUri())
                && path.getMethod().equals(httpRequestDTO.getMethod()));
    }
```

**Fed by:**

- [x] change "/players/game/id" to "/players/id/game" or similar
- [x] change "/players/games/id" to "/players/id/games" or similar
- [x] regex adjustments 

```
eureka:
  admin-paths:
    paths:
      - uri: "/players"
        method: "POST"
      - uri: "/players/game/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/players/update/{1}[1-9]+[0-9]*"
        method: "PUT"
      - uri: "/players/update/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/players/update/rate/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/players/games/{1}[1-9]+[0-9]*"
        method: "DELETE"
```

**Through this Class:**

- [x] stay as it is

```
public class HttpRequestDTO {
    private String uri;
    private String method;
}
```

- [x] Finally, adjust Service (rest template calls) and Controller method

How I can do to modify this to support the following path? Lets check
